---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.visonneau.fr
      chart: tailscale-relay
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/mvisonneau/tailscale
      tag: 'v1.30.1'
    config:
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "${NETWORK_K8S_CLUSTER_CIDR},${NETWORK_K8S_SERVICE_CIDR}"
  valuesFrom:
    - kind: Secret
      name: tailscale-token-secret
      valuesKey: tailscale-token
      targetPath: config.authKey
