---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotenberg
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kurt108.github.io/helm-charts
      chart: gotenberg
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: kurt108
        namespace: flux-system
      interval: 5m
