---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trino
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://trinodb.github.io/charts/
      chart: trino
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: flux-system
      interval: 5m
